package com.ixume.armorhud;

import org.bukkit.Material;

public enum SlotEnum {
    HELMET,
    CHESTPLATE,
    LEGGINGS,
    BOOTS,
    MAIN,
    OFF;

    public static SlotEnum getEnum(Material type) {
        return switch (type) {
            case LEATHER_HELMET, CHAINMAIL_HELMET, GOLDEN_HELMET, IRON_HELMET, DIAMOND_HELMET, NETHERITE_HELMET -> SlotEnum.HELMET;
            case LEATHER_CHESTPLATE, CHAINMAIL_CHESTPLATE, GOLDEN_CHESTPLATE, IRON_CHESTPLATE, DIAMOND_CHESTPLATE, NETHERITE_CHESTPLATE -> SlotEnum.CHESTPLATE;
            case LEATHER_LEGGINGS, CHAINMAIL_LEGGINGS, GOLDEN_LEGGINGS, IRON_LEGGINGS, DIAMOND_LEGGINGS, NETHERITE_LEGGINGS -> SlotEnum.LEGGINGS;
            case LEATHER_BOOTS, CHAINMAIL_BOOTS, GOLDEN_BOOTS, IRON_BOOTS, DIAMOND_BOOTS, NETHERITE_BOOTS -> SlotEnum.BOOTS;
            case WOODEN_SWORD, STONE_SWORD, GOLDEN_SWORD, IRON_SWORD, DIAMOND_SWORD, NETHERITE_SWORD -> SlotEnum.MAIN;
            default -> null;
        };
    }
}
